# Generated by Django 2.2.5 on 2019-10-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190929_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='encoding',
            field=models.DateField(blank=True, null=True),
        ),
    ]
