# Generated by Django 2.2.5 on 2019-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_images_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='encoding',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
